name: infinz
description: Infinz - Your Financial Advisor
version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pin_code_fields: ^8.0.0
  file_picker: ^10.2.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  localstorage: ^6.0.0
  intl: ^0.18.1
  http: ^1.1.0



  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_otp_text_field: ^1.1.3+2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1
  another_telephony: ^0.4.1
  animated_bottom_navigation_bar: ^1.4.0
  sign_in_with_apple: ^7.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/Cashmate-logo.png
    - assets/lottie/Money.json
    - assets/image/new-logo.png