// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIK-VN2aaoUb4YOq6pN97LvsgK9PgXFfg',
    appId: '1:792116662636:web:54662f4a58d50cc0c9a349',
    messagingSenderId: '792116662636',
    projectId: 'cashmate-app-2bc3f',
    authDomain: 'cashmate-app-2bc3f.firebaseapp.com',
    storageBucket: 'cashmate-app-2bc3f.firebasestorage.app',
    measurementId: 'G-JCSCERG1GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLdTIWxg9Vto1IfSFNCpYkIGJCJkWwRK8',
    appId: '1:792116662636:android:e303e68ccd806a6cc9a349',
    messagingSenderId: '792116662636',
    projectId: 'cashmate-app-2bc3f',
    storageBucket: 'cashmate-app-2bc3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXskb7Pig_fKcAikgTMdpj9f2BK0iz-SM',
    appId: '1:792116662636:ios:caddbf7394a40a6dc9a349',
    messagingSenderId: '792116662636',
    projectId: 'cashmate-app-2bc3f',
    storageBucket: 'cashmate-app-2bc3f.firebasestorage.app',
    androidClientId: '792116662636-5d9t6uqtl5k1vg9j2pm02r0asdpiclgu.apps.googleusercontent.com',
    iosClientId: '792116662636-tli39v9ouj9mu4nuf1bjtiathp2or45g.apps.googleusercontent.com',
    iosBundleId: 'com.cashmate.loan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXskb7Pig_fKcAikgTMdpj9f2BK0iz-SM',
    appId: '1:792116662636:ios:0b8fd0d03612579ec9a349',
    messagingSenderId: '792116662636',
    projectId: 'cashmate-app-2bc3f',
    storageBucket: 'cashmate-app-2bc3f.firebasestorage.app',
    androidClientId: '792116662636-5d9t6uqtl5k1vg9j2pm02r0asdpiclgu.apps.googleusercontent.com',
    iosClientId: '792116662636-euneu0h1qdrvts3ra4hum5u4d9l91vfi.apps.googleusercontent.com',
    iosBundleId: 'com.cashmate.cashmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIK-VN2aaoUb4YOq6pN97LvsgK9PgXFfg',
    appId: '1:792116662636:web:6476c0f23817f5afc9a349',
    messagingSenderId: '792116662636',
    projectId: 'cashmate-app-2bc3f',
    authDomain: 'cashmate-app-2bc3f.firebaseapp.com',
    storageBucket: 'cashmate-app-2bc3f.firebasestorage.app',
    measurementId: 'G-1VHXZQ0ZMC',
  );
}
